### ISSUE TITLE
Trait to get bounds from `&T`?

### ISSUE THREAD

**Issue by grovesNL** [Ralith/sieve-tree#19]
We accept `get_bounds: impl FnMut(&T) -> Bounds<DIM>` in a few functions. With the planned traversals we'll probably need this in a few other places too.

Instead of accepting a closure for these, would it make sense to have a `GetBounds` trait that can produce a `Bounds<DIM>` from `&T` instead? We could limit those functions to types with `T: GetBounds` and remove the closure as an argument.

Most of the time the closure is trivial so it's something like `|b| *b` or `|b| b.bounds`, but it could be nice implement this once on the type instead of passing it. We could also do `impl<const DIM: usize> GetBounds<DIM> for Bounds<DIM>` which would be convenient for the trivial case where we're only working with `Bounds`.

**Comment by Ralith** [comment]
The choice to use a closure here was deliberate. The core notional use-case for this structure is to index data that is owned elsewhere and organized differently, e.g. rapier's `ColliderSet`. In those cases, the bounds might already be stored, or readily computed based on data stored, elsewhere. Exposing external data through a trait on `T` would likely be much more awkward than passing in a closure which captures a borrow of the external data.

**Comment by grovesNL** [comment]
Alright sounds good, thanks for clarifying - I thought there was some kind of reasoning like that behind the closure.

I guess we could pass in some kind of context for these functions and in turn pass it to the trait (e.g., `fn get_bounds<Context>(id: usize, context: &Context)` to pass `ColliderSet` down, although that might be more awkward than using closures anyway.

**Comment by Ralith** [comment]
Yeah, exactly. At least this way it's immediately apparent what the extra argument is for.
