### ISSUE TITLE
`remove` will remove the element before its successor is loaded in `unlink`

### ISSUE THREAD

**Issue by grovesNL** [Ralith/sieve-tree#2]
`remove` starts off by removing it from `elements`
https://github.com/Ralith/sieve-tree/blob/460fd6aa4a416a9de1614b7a0da625b29300cbb3/src/lib.rs#L223
but later calls `unlink`. `unlink` tries to load the successor of the deleted element (`let successor = elements[element].next;`) but this is too late.

It looks like moving `let elt = self.elements.remove(id);` after `unlink` should work fine.

**Comment by grovesNL** [comment]
Something like this should reproduce it
```rust
#[test]
fn remove() {
    let mut tree = SieveTree::<1, 2, Bounds<1>>::new();
    let bounds = Bounds::point([0.]);
    let id = tree.insert(bounds, bounds);
    assert_eq!(tree.remove(bounds, id), bounds);
}
```

**Comment by Ralith** [comment]
Fixed, thanks!
