### ISSUE TITLE
Intersection testing with bounds below `origin` may include extra intersections

### ISSUE THREAD

**Issue by grovesNL** [Ralith/sieve-tree#20]
If we have a test case like this:
```rust
#[test]
fn regression3() {
    let mut t = SieveTree::<1, 2, Bounds<1>>::with_granularity(1.);
    let b1 = Bounds {
        min: [10.],
        max: [11.],
    };
    t.insert(b1, b1);

    let intersections = t
        .intersections(Bounds {
            min: [1.],
            max: [2.],
        })
        .map(|(_, bounds)| *bounds)
        .collect::<alloc::vec::Vec<_>>();

    assert_eq!(intersections, []);
}
```

This creates a tree with an origin of 10. When we do intersection testing from world bounds 1..2 though, we convert to tree bounds using that origin. This ends up creating negative `f64`s that are cast to a `u64`, so the tree bounds for intersection become 0..0. The intersection of 0..0 then incorrectly finds an intersection with `b1`.

Technically there should always finer grained intersection testing on the results from `intersections`, but it still seems like we could do something better here. For example, knowing that the max tree bound is outside the tree could allow us to skip intersection testing entirely for this case.

We could also consider shifting the entire tree at the start of `intersections` by calling `ensure_origin_precedes` using the intersections' `min`, so that we can fit the bounds we're trying to test. It might be too weird for `intersections` to take `&mut self` though.

**Comment by Ralith** [comment]
> knowing that the max tree bound is outside the tree could allow us to skip intersection testing entirely for this case.

That seems like a good solution to me. `Intersections` is built in a way that makes it straightforward to construct an empty iterator.
