### ISSUE TITLE
Round-tripping world bounds and tree bounds gives different results

### ISSUE THREAD

**Issue by grovesNL** [Ralith/sieve-tree#21]
If we have a test case like:
```rust
#[test]
fn round_trip_world_tree_bounds() {
    let world = Bounds {
        min: [10.0, 20.0],
        max: [30.0, 40.0],
    };
    let granularity = 1.0;
    let embedding = Embedding {
        origin: [0.0, 0.0],
    };
    let tree = embedding.bounds_from_world(granularity, &world);
    let world2 = embedding.world_bounds_from_tree(granularity, &tree);
    assert_eq!(world, world2);
}
```

We get:
```
assertion `left == right` failed
  left: Bounds { min: [10.0, 20.0], max: [30.0, 40.0] }
 right: Bounds { min: [10.0, 20.0], max: [31.0, 41.0] }
 ```
 
This is because `world_bounds_from_tree` calculates `max` using `max: self.world_from_tree(granularity, &tree.max.map(|x| x + 1)),`, but `bounds_from_world` uses `self.tree_from_world(granularity, &world.max),` (without an additional offset).

I guess the idea is that tree bounds are supposed to be max-inclusive while world bounds are max-exclusive. If that's the case then we'd want to subtract 1 in `bounds_from_world`.

**Comment by Ralith** [comment]
Per docs, both `Bounds` and `TreeBounds` are inclusive, but inclusive/exclusive don't mean much in `f64`.

**Comment by Ralith** [comment]
I think this is just an unavoidable consequence of quantizing coordinates conservatively. Every input must get "rounded up" to the bounds of the discrete level-0 cells that it overlaps with.

The `max` value computed by `world_bounds_from_tree` is never used except in the `SieveTree::bounds` getter, so it'd be quite difficult to put yourself in a position where you're round-tripping these, anyway.

**Comment by grovesNL** [comment]
Makes sense, thanks! I totally missed that the `+ 1` was meant to help with quantization.

**Comment by Ralith** [comment]
A good way to build intuition is to consider the behavior for `Bounds` representing a point (i.e. `min = max`).
