### ISSUE TITLE
Entire tree traversal

### ISSUE THREAD

**Issue by grovesNL** [Ralith/sieve-tree#7]
This probably shouldn't be used often, but in some cases (even just external tests) it would be useful to have something like a entire tree iterator to iterate over all `(id, bounds)` pairs.

**Comment by Ralith** [comment]
The tree doesn't actually know the bounds of an element, just an upper bound. Would you want that?

**Comment by grovesNL** [comment]
The bounds would be useful to be able to queue (after traversal) some elements for removal based on their values, so I guess the upper bound would work for that, right?

**Comment by Ralith** [comment]
Ah, that makes sense, yeah.

**Comment by Ralith** [comment]
Counterpoint: why not fetch the bound from the `T`, as you're generally presumed to be able to do efficiently?

**Comment by grovesNL** [comment]
Yeah that sounds good, so the iterator could either return `usize` (look up the `&T` with `get`) or `(usize, &T)` pairs

**Comment by Ralith** [comment]
Probably `(usize, &T)`, so that the `iter_mut` variant can yield a `&mut T` while the iterator is live.

**Comment by Ralith** [comment]
Implemented naively in 3d1bc7a31a737abec88eb30eb625de92fbc59153.
